"""Seed 224 Russian product variants from data/russian_variants.json (generated by Claude Sonnet).
KBJU values reviewed against USDA / Russian SanPiN references.
"""
import asyncio
import json
import os
import sys
from uuid import uuid4

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


async def seed(db_url: str | None = None):
    from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker
    from sqlalchemy import select
    from app.models.product import Product

    url = db_url or os.environ.get("DATABASE_URL", "sqlite+aiosqlite:///nutrition_diary.db")
    if url.startswith("postgres://"):
        url = url.replace("postgres://", "postgresql://", 1)
    if url.startswith("postgresql://"):
        url = url.replace("postgresql://", "postgresql+asyncpg://", 1)

    data_path = os.path.join(os.path.dirname(__file__), "..", "data", "russian_variants.json")
    products = json.load(open(data_path, encoding="utf-8"))

    engine = create_async_engine(url, echo=False)
    Session = async_sessionmaker(engine, expire_on_commit=False)

    added = 0
    skipped = 0
    async with Session() as s:
        for p in products:
            name = p.get("name", "").strip()
            if not name:
                continue
            existing = (await s.execute(
                select(Product).where(Product.name == name)
            )).scalar_one_or_none()
            if existing:
                skipped += 1
                continue
            s.add(Product(
                id=uuid4(),
                name=name,
                category=p.get("category"),
                source="manual_ru",
                serving_size=100.0,
                serving_unit="g",
                calories=float(p.get("calories") or 0),
                protein=float(p.get("protein") or 0),
                fat=float(p.get("fat") or 0),
                carbohydrates=float(p.get("carbohydrates") or 0),
                fiber=p.get("fiber"),
                is_verified=True,
            ))
            added += 1
        await s.commit()
    await engine.dispose()
    print(f"[ru_variants] added={added} skipped={skipped}")


if __name__ == "__main__":
    asyncio.run(seed())
