# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None
# Spec is in desktop/, project root is one level up
ROOT = os.path.abspath(os.path.join(SPECPATH, '..'))

a = Analysis(
    [os.path.join(ROOT, 'desktop', 'app_exe.py')],
    pathex=[ROOT],
    binaries=[],
    datas=[
        (os.path.join(ROOT, 'app', 'templates'), 'app/templates'),
        (os.path.join(ROOT, 'app', 'static'), 'app/static'),
        (os.path.join(ROOT, 'app', 'api'), 'app/api'),
        (os.path.join(ROOT, 'app', 'core'), 'app/core'),
        (os.path.join(ROOT, 'app', 'db'), 'app/db'),
        (os.path.join(ROOT, 'app', 'models'), 'app/models'),
        (os.path.join(ROOT, 'app', 'schemas'), 'app/schemas'),
        (os.path.join(ROOT, 'app', 'services'), 'app/services'),
        (os.path.join(ROOT, 'scripts'), 'scripts'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'aiosqlite',
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.dialects.sqlite.aiosqlite',
        'app.main',
        'app.core.config',
        'app.core.security',
        'app.core.deps',
        'app.db.base',
        'app.db.session',
        'app.db.compat',
        'app.models.user',
        'app.models.product',
        'app.models.diary',
        'app.models.health',
        'app.models.device',
        'app.api.v1.router',
        'app.api.v1.endpoints.auth',
        'app.api.v1.endpoints.products',
        'app.api.v1.endpoints.diary',
        'app.api.v1.endpoints.meals',
        'app.api.v1.endpoints.barcode',
        'app.api.v1.endpoints.stats',
        'app.api.v1.endpoints.nutrients',
        'app.api.v1.endpoints.health',
        'app.api.v1.endpoints.devices',
        'app.api.v1.endpoints.food_scan',
        'app.api.v1.endpoints.export',
        'app.api.v1.endpoints.share',
        'app.api.v1.endpoints.bot',
        'app.api.v1.endpoints.recommendations',
        'app.api.v1.endpoints.sync',
        'app.schemas.auth',
        'app.schemas.product',
        'app.services.product_service',
        'app.services.food_recognition_service',
        'scripts.seed_products',
        'scripts.seed_conditions',
        'scripts.seed_vitamins',
        'scripts.db_helper',
        'email_validator',
        'pydantic',
        'pydantic_settings',
        'bcrypt',
        'jose',
        'httpx',
        'multipart',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'asyncpg',
        'psycopg2',
        'redis',
        'passlib',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='NutritionDiary',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='NutritionDiary',
)
